apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    CREATE USER '${APP_USER}'@'%' IDENTIFIED BY '${USER_PASSWORD}';
    GRANT ALL PRIVILEGES ON mydb.* TO '${APP_USER}'@'%';
    FLUSH PRIVILEGES;
