apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mysql-infisical
  namespace: mysql
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: mysql
      secretsScope:
        projectId: 7f77ea6e-c225-4c3a-844e-039f6467f07f
        envSlug: dev
        secretsPath: /mysql
  managedKubeSecretReferences:
    - secretName: mysql-secret
      secretNamespace: mysql
      creationPolicy: "Orphan"
